FROM node:20-alpine

WORKDIR /app

# npm 관련 패키지 복사 및 설치
COPY package.json package-lock.json* ./
RUN npm install

# 애플리케이션 코드 복사
COPY . .

# Vite 포트 노출
EXPOSE 5173

# HMR을 위해 host 개방 모드로 개발 서버 시작
CMD ["npm", "run", "dev", "--", "--host"]
