import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'intro',
    {
      type: 'category',
      label: '기획문서',
      collapsed: false,
      items: [
        'planning/world-map-overview',
        'planning/world-map-weather',
        'planning/world-map-fuel',
        'planning/quest-completion',
      ],
    },
    {
      type: 'category',
      label: 'Services',
      items: [
        'services/overview',
        'services/frontend',
        'services/bff',
        'services/engine',
      ],
    },
    {
      type: 'category',
      label: 'Private (Auth Required)',
      collapsed: false,
      items: [
        'private/architecture',
        'private/database',
        'private/server-spec',
        {
          type: 'category',
          label: 'Test / QA',
          collapsed: false,
          items: [
            { type: 'autogenerated', dirName: 'private/test' },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
