#!/usr/bin/env python3
import hashlib
import json
import sys
import urllib.request
from pathlib import Path

SOURCE_URL = (
    "https://media.githubusercontent.com/media/wmgeolab/geoBoundaries/9469f09/"
    "releaseData/gbOpen/VNM/ADM2/geoBoundaries-VNM-ADM2.geojson"
)
SOURCE_SHA256 = "17db305257c1794fb5f3f4ff3c4f747a07cc5525774b8edb395d53f65219fc33"

DISTRICT_SHAPE_IDS = {
    "BINH_CHANH": ("81297802B93683261125538",),
    "BINH_TAN": ("81297802B42527210401893",),
    "BINH_THANH": ("81297802B74412015974526",),
    "CAN_GIO": ("81297802B7702852417854",),
    "CU_CHI": ("81297802B99873561685500",),
    "GO_VAP": ("81297802B93588362587103",),
    "HOC_MON": ("81297802B64363050509880",),
    "NHA_BE": ("81297802B80984092880643",),
    "PHU_NHUAN": ("81297802B72603937188235",),
    "QUAN_1": ("81297802B34545275526363",),
    "QUAN_10": ("81297802B93335721036450",),
    "QUAN_11": ("81297802B37641712637141",),
    "QUAN_12": ("81297802B78652503258302",),
    "QUAN_3": ("81297802B4427483692725",),
    "QUAN_4": ("81297802B29563104023098",),
    "QUAN_5": ("81297802B17569327634169",),
    "QUAN_6": ("81297802B35379290873600",),
    "QUAN_7": ("81297802B84259990428862",),
    "QUAN_8": ("81297802B52284124086366",),
    "TAN_BINH": ("81297802B72151759297882",),
    "TAN_PHU": ("81297802B97138813252769",),
    "THU_DUC": (
        "81297802B76466747653960",
        "81297802B54605917200404",
        "81297802B1678031067910",
    ),
}


def download_source() -> bytes:
    with urllib.request.urlopen(SOURCE_URL, timeout=60) as response:  # noqa: S310 -- pinned HTTPS source
        return response.read()


def generate(source: bytes) -> str:
    digest = hashlib.sha256(source).hexdigest()
    if digest != SOURCE_SHA256:
        raise ValueError(f"source SHA-256 mismatch: {digest}")

    features = json.loads(source)["features"]
    by_id = {feature["properties"]["shapeID"]: feature for feature in features}
    rows = []
    for code, shape_ids in DISTRICT_SHAPE_IDS.items():
        for shape_id in shape_ids:
            feature = by_id.get(shape_id)
            if feature is None:
                raise ValueError(f"missing shapeID: {shape_id}")
            geometry = json.dumps(feature["geometry"], ensure_ascii=False, separators=(",", ":"))
            rows.append(f"    ('{code}', '{shape_id}', $geo${geometry}$geo$::jsonb)")

    values = ",\n".join(rows)
    return f"""-- Generated by tools/generate_legacy_district_boundaries.py; do not edit by hand.
-- Source SHA-256: {SOURCE_SHA256}
-- Legacy pre-2025 HCMC district contract. THU_DUC merges 2020 Quan 2, Quan 9 and Thu Duc.

BEGIN;

CREATE TEMP TABLE _legacy_district_boundary_source (
    code VARCHAR(30) NOT NULL,
    shape_id VARCHAR(40) NOT NULL,
    geometry JSONB NOT NULL
) ON COMMIT DROP;

INSERT INTO _legacy_district_boundary_source (code, shape_id, geometry) VALUES
{values};

DO $$
DECLARE
    source_count INTEGER;
    district_count INTEGER;
BEGIN
    SELECT COUNT(DISTINCT code) INTO source_count FROM _legacy_district_boundary_source;
    SELECT COUNT(*) INTO district_count
    FROM districts d
    JOIN (SELECT DISTINCT code FROM _legacy_district_boundary_source) s USING (code);
    IF source_count <> 22 OR district_count <> 22 THEN
        RAISE EXCEPTION 'legacy district mapping incomplete: source=%, districts=%', source_count, district_count;
    END IF;
END $$;

DO $$
DECLARE
    valid_count INTEGER;
    overlap_count INTEGER;
BEGIN
    WITH parsed AS (
        SELECT code, ST_MakeValid(ST_SetSRID(ST_GeomFromGeoJSON(geometry::text), 4326)) AS geom
        FROM _legacy_district_boundary_source
    ), merged AS (
        SELECT code, ST_UnaryUnion(ST_Collect(geom)) AS geom
        FROM parsed
        GROUP BY code
    )
    SELECT COUNT(*) INTO valid_count
    FROM merged
    WHERE ST_IsValid(geom)
      AND GeometryType(geom) = 'POLYGON'
      AND ST_Area(geom::geography) > 1000000;

    WITH parsed AS (
        SELECT code, ST_MakeValid(ST_SetSRID(ST_GeomFromGeoJSON(geometry::text), 4326)) AS geom
        FROM _legacy_district_boundary_source
    ), merged AS (
        SELECT code, ST_UnaryUnion(ST_Collect(geom)) AS geom
        FROM parsed
        GROUP BY code
    )
    SELECT COUNT(*) INTO overlap_count
    FROM merged a
    JOIN merged b ON a.code < b.code
    WHERE ST_Area(ST_Intersection(a.geom, b.geom)::geography) > 1;

    IF valid_count <> 22 OR overlap_count <> 0 THEN
        RAISE EXCEPTION 'legacy source geometry invalid: valid=%/22, overlaps=%', valid_count, overlap_count;
    END IF;
END $$;

WITH parsed AS (
    SELECT code, ST_MakeValid(ST_SetSRID(ST_GeomFromGeoJSON(geometry::text), 4326)) AS geom
    FROM _legacy_district_boundary_source
), merged AS (
    SELECT code, ST_UnaryUnion(ST_Collect(geom)) AS geom
    FROM parsed
    GROUP BY code
), validated AS (
    SELECT code, geom
    FROM merged
    WHERE ST_IsValid(geom)
      AND GeometryType(geom) = 'POLYGON'
      AND ST_Area(geom::geography) > 1000000
)
UPDATE districts d
SET boundary = v.geom::geography,
    center_lat = ST_Y(ST_PointOnSurface(v.geom)),
    center_lng = ST_X(ST_PointOnSurface(v.geom))
FROM validated v
WHERE d.code = v.code;

DO $$
DECLARE
    updated_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO updated_count
    FROM districts d
    JOIN (SELECT DISTINCT code FROM _legacy_district_boundary_source) s USING (code)
    WHERE d.boundary IS NOT NULL
      AND ST_IsValid(d.boundary::geometry)
      AND ST_Area(d.boundary) > 1000000
      AND ST_Covers(d.boundary, ST_SetSRID(ST_MakePoint(d.center_lng, d.center_lat), 4326)::geography);
    IF updated_count <> 22 THEN
        RAISE EXCEPTION 'legacy district boundary validation failed: %/22', updated_count;
    END IF;
END $$;

COMMIT;
"""


def main() -> None:
    if len(sys.argv) not in (2, 3):
        raise SystemExit("usage: generate_legacy_district_boundaries.py OUTPUT.sql [SOURCE.geojson]")
    source = Path(sys.argv[2]).read_bytes() if len(sys.argv) == 3 else download_source()
    Path(sys.argv[1]).write_text(generate(source), encoding="utf-8")


if __name__ == "__main__":
    main()
