/* @section: product-demo-system */
import type { ReactNode } from "react";
import {
  BarChart3,
  Check,
  ChevronDown,
  CircleAlert,
  Clock3,
  Code2,
  Database,
  FileCheck2,
  LayoutDashboard,
  ListChecks,
  MessageSquareText,
  Play,
  Search,
  ShieldCheck,
  Sparkles,
  Table2,
  UserCheck,
} from "lucide-react";

export type ProductDemoView = "ask" | "hitl" | "sql" | "dashboard" | "audit" | "inspector";
export type ProductDemoMode = "full" | "compact" | "evidence";

const VIEW_META: Record<ProductDemoView, { label: string; icon: typeof MessageSquareText }> = {
  ask: { label: "AI Ask", icon: MessageSquareText },
  hitl: { label: "HITL 검토", icon: UserCheck },
  sql: { label: "SQL 투명성", icon: Code2 },
  dashboard: { label: "대시보드", icon: LayoutDashboard },
  audit: { label: "감사 로그", icon: ListChecks },
  inspector: { label: "SQL Inspector", icon: Search },
};

const PRODUCT_DEMO_STYLES = `
  .pd-frame{--pd-bg:#060b12;--pd-panel:#0b121c;--pd-panel-2:#0e1722;--pd-line:rgba(148,163,184,.16);--pd-text:#e7edf5;--pd-muted:#8090a3;--pd-blue:#36bdf5;--pd-green:#4ade80;position:relative;min-width:0;overflow:hidden;border:1px solid rgba(148,197,255,.2);border-radius:26px;background:var(--pd-bg);color:var(--pd-text);box-shadow:0 24px 64px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.04);font-family:var(--font-sans);text-align:left}
  .pd-frame *{box-sizing:border-box}.pd-frame button{font:inherit}.pd-mono{font-family:var(--font-mono)}
  .pd-window{height:38px;display:flex;align-items:center;gap:6px;padding:0 13px;border-bottom:1px solid var(--pd-line);background:#101720}.pd-window__dot{width:8px;height:8px;border-radius:50%}.pd-window__dot:nth-child(1){background:#ff6158}.pd-window__dot:nth-child(2){background:#ffbd2d}.pd-window__dot:nth-child(3){background:#28c941}.pd-window__title{margin-left:9px;color:#667487;font-size:10px;letter-spacing:.04em}.pd-window__status{display:flex;align-items:center;gap:5px;margin-left:auto;color:#55d990;font-size:9px}.pd-window__status i{width:5px;height:5px;border-radius:50%;background:#4ade80;box-shadow:0 0 8px #4ade80}
  .pd-app{display:grid;grid-template-columns:124px minmax(0,1fr);min-height:0;align-items:start}.pd-sidebar{align-self:stretch;padding:13px 9px;border-right:1px solid var(--pd-line);background:#080d14}.pd-brand{display:flex;align-items:center;gap:7px;padding:5px 6px 14px;font-size:11px;font-weight:750}.pd-brand__mark{display:grid;width:22px;height:22px;place-items:center;border-radius:7px;background:linear-gradient(135deg,#1d4ed8,#38bdf8);font-size:10px}.pd-side-label{padding:8px 7px 5px;color:#465364;font-size:7px;letter-spacing:.12em}.pd-nav{display:grid;gap:3px}.pd-nav__item{display:flex;align-items:center;gap:7px;padding:7px;border-radius:7px;color:#657386;font-size:9px}.pd-nav__item--active{color:#dceaff;background:rgba(14,165,233,.12)}.pd-nav__item svg{width:11px;height:11px}.pd-sidebar__foot{margin-top:18px;padding:9px 7px;border-top:1px solid var(--pd-line);color:#536174;font-size:8px;line-height:1.6}
  .pd-workspace{min-width:0;background:linear-gradient(145deg,#070c13,#09111a)}.pd-toolbar{height:42px;display:flex;align-items:center;gap:8px;padding:0 14px;border-bottom:1px solid var(--pd-line);background:rgba(7,12,19,.88)}.pd-toolbar__title{display:flex;align-items:center;gap:7px;font-size:11px;font-weight:700}.pd-toolbar__title svg{width:13px;height:13px;color:var(--pd-blue)}.pd-chip{display:inline-flex;align-items:center;gap:5px;padding:4px 7px;border:1px solid var(--pd-line);border-radius:999px;color:#718196;font-size:8px;white-space:nowrap}.pd-chip--safe{margin-left:auto;border-color:rgba(74,222,128,.18);color:#55d990;background:rgba(74,222,128,.055)}.pd-chip--safe i{width:4px;height:4px;border-radius:50%;background:#4ade80}.pd-avatar{display:grid;width:22px;height:22px;place-items:center;border-radius:50%;background:#162333;color:#8fa1b5;font-size:7px}
  .pd-content{min-width:0;padding:16px}.pd-query{display:flex;align-items:center;gap:8px;padding:10px 12px;border:1px solid var(--pd-line);border-radius:9px;background:#0b131b;color:#dce5ef;font-size:11px}.pd-query svg{width:13px;height:13px;color:var(--pd-blue);flex:0 0 auto}.pd-query__cursor{width:1px;height:12px;background:var(--pd-blue);animation:pdBlink 1s step-end infinite}.pd-kicker{display:flex;align-items:center;gap:7px;color:#5f6e81;font-size:8px;letter-spacing:.08em;text-transform:uppercase}.pd-kicker svg{width:11px;height:11px;color:var(--pd-blue)}.pd-card{min-width:0;border:1px solid var(--pd-line);border-radius:10px;background:rgba(13,21,31,.86)}.pd-card__head{display:flex;align-items:center;gap:7px;min-height:34px;padding:0 11px;border-bottom:1px solid var(--pd-line);font-size:9px;font-weight:700}.pd-card__head span:last-child{margin-left:auto;color:#536174;font-size:8px;font-weight:500}.pd-grid-2{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(150px,.7fr);gap:10px;margin-top:10px}.pd-stack{display:grid;gap:10px}.pd-answer{padding:12px}.pd-answer__lead{display:flex;align-items:flex-start;gap:8px;color:#cbd8e6;font-size:10px;line-height:1.6}.pd-answer__lead svg{width:14px;height:14px;flex:0 0 auto;color:var(--pd-blue)}.pd-answer strong{color:#fff}.pd-source{display:flex;flex-wrap:wrap;gap:5px;margin-top:10px}.pd-source span{padding:4px 6px;border:1px solid rgba(54,189,245,.18);border-radius:5px;color:#72caed;background:rgba(54,189,245,.05);font-size:7px}
  .pd-table{width:100%;border-collapse:collapse;table-layout:fixed}.pd-table th,.pd-table td{padding:7px 9px;border-bottom:1px solid rgba(148,163,184,.1);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:8px;text-align:left}.pd-table th{color:#5e6d80;font-weight:550}.pd-table td{color:#a9b6c5}.pd-table td:last-child,.pd-table th:last-child{text-align:right}.pd-table tr:last-child td{border-bottom:0}.pd-value{color:#62c5ec!important}.pd-status{display:inline-flex;align-items:center;gap:4px;color:#4ade80}.pd-status--wait{color:#fbbf24}.pd-status--deny{color:#fb7185}.pd-status i{width:4px;height:4px;border-radius:50%;background:currentColor}
  .pd-metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.pd-metric{padding:10px}.pd-metric span{display:block;color:#647489;font-size:7px}.pd-metric strong{display:block;margin-top:5px;font-size:15px;letter-spacing:-.03em}.pd-metric em{display:block;margin-top:4px;color:#4ade80;font-size:7px;font-style:normal}.pd-chart{position:relative;height:118px;padding:18px 10px 10px}.pd-chart::before{content:"";position:absolute;inset:16px 10px 20px;background-image:linear-gradient(rgba(148,163,184,.1) 1px,transparent 1px);background-size:100% 25%}.pd-bars{position:relative;z-index:1;display:flex;height:100%;align-items:flex-end;gap:8px}.pd-bar{flex:1;min-width:0;border-radius:4px 4px 1px 1px;background:linear-gradient(180deg,#38bdf8,#1d4ed8);box-shadow:0 0 14px rgba(56,189,248,.1)}.pd-bar:nth-child(2n){background:linear-gradient(180deg,#60a5fa,#2563eb)}.pd-bars span{position:absolute;bottom:-12px;color:#526176;font-size:6px}.pd-donut{display:grid;place-items:center;padding:12px}.pd-donut svg{width:94px;max-width:100%;height:auto}.pd-donut text{fill:#dfe8f2;font-size:10px;font-family:var(--font-sans);font-weight:750}.pd-legend{display:grid;gap:6px;padding:0 12px 12px}.pd-legend span{display:flex;align-items:center;gap:6px;color:#728197;font-size:7px}.pd-legend i{width:6px;height:6px;border-radius:50%}
  .pd-code{padding:11px;background:#050910;color:#58c3ec;font-size:8px;line-height:1.7;overflow:auto;white-space:pre}.pd-code .kw{color:#a78bfa}.pd-code .st{color:#86efac}.pd-gates{display:flex;flex-wrap:wrap;gap:6px;padding:9px 10px;border-top:1px solid var(--pd-line)}.pd-gate{display:flex;align-items:center;gap:4px;color:#55d990;font-size:7px}.pd-review{display:grid;grid-template-columns:minmax(0,1fr) 160px;gap:10px;margin-top:10px}.pd-review__panel{display:grid;gap:9px;padding:11px}.pd-review__row{display:grid;grid-template-columns:74px 1fr;gap:8px;color:#9ba9b9;font-size:8px;line-height:1.5}.pd-review__row b{color:#58677a;font-weight:550}.pd-risk{padding:9px;border:1px solid rgba(251,191,36,.17);border-radius:8px;color:#d6b65d;background:rgba(251,191,36,.045);font-size:8px;line-height:1.55}.pd-actions{display:flex;gap:6px;margin-top:auto}.pd-action{display:inline-flex;flex:1;align-items:center;justify-content:center;gap:4px;min-height:30px;border:1px solid var(--pd-line);border-radius:7px;color:#8190a3;background:#0b131c;font-size:8px}.pd-action--primary{border-color:rgba(54,189,245,.3);color:#d9f4ff;background:rgba(14,165,233,.13)}.pd-action svg{width:10px;height:10px}
  .pd-sql-layout{display:grid;grid-template-columns:minmax(0,1fr) 158px;gap:10px;margin-top:10px}.pd-lineage{padding:11px}.pd-lineage__node{padding:8px;border:1px solid var(--pd-line);border-radius:7px;background:#0a121b}.pd-lineage__node b{display:block;color:#9fb0c2;font-size:8px}.pd-lineage__node span{display:block;margin-top:3px;color:#516175;font-size:7px}.pd-lineage__arrow{height:20px;display:grid;place-items:center;color:#3b8fb3;font-size:9px}.pd-inspector{display:grid;grid-template-columns:90px minmax(0,1fr);min-height:0}.pd-inspector__files{padding:10px;border-right:1px solid var(--pd-line);background:#080e16}.pd-inspector__files span{display:block;padding:6px;border-radius:5px;color:#617186;font-size:7px}.pd-inspector__files span:first-child{color:#c3d6e9;background:rgba(54,189,245,.09)}.pd-editor{min-width:0;background:#050910}.pd-editor__tabs{display:flex;min-height:31px;border-bottom:1px solid var(--pd-line)}.pd-editor__tabs span{padding:10px;color:#607085;font-size:7px}.pd-editor__tabs span:first-child{color:#d0deeb;border-right:1px solid var(--pd-line);background:#0b121b}.pd-editor__body{display:grid;grid-template-columns:24px 1fr;padding:10px 0}.pd-lines{color:#334154;font-size:7px;line-height:1.9;text-align:right}.pd-editor pre{margin:0;padding:0 10px;color:#58c3ec;font-size:7px;line-height:1.9;white-space:pre-wrap}.pd-editor__foot{display:flex;align-items:center;gap:8px;margin:0 10px 10px;padding:8px;border:1px solid rgba(74,222,128,.15);border-radius:6px;color:#55d990;font-size:7px;background:rgba(74,222,128,.035)}
  .pd-frame--compact .pd-app{grid-template-columns:1fr;min-height:0}.pd-frame--compact .pd-sidebar{display:none}.pd-frame--compact .pd-toolbar{display:none}.pd-frame--compact .pd-content{padding:12px}.pd-frame--compact .pd-window__status{display:none}.pd-frame--compact .pd-grid-2{grid-template-columns:minmax(0,1.3fr) minmax(132px,.7fr)}
  .pd-frame--evidence{border:0;border-radius:0;box-shadow:none}.pd-frame--evidence .pd-window,.pd-frame--evidence .pd-sidebar{display:none}.pd-frame--evidence .pd-app{display:block;min-height:0}.pd-frame--evidence .pd-toolbar{height:38px}.pd-frame--evidence .pd-content{padding:10px}.pd-frame--evidence .pd-chip:not(.pd-chip--safe),.pd-frame--evidence .pd-avatar{display:none}.pd-frame--evidence .pd-grid-2{gap:8px;margin-top:8px}
  .pd-frame[data-product-demo="inspector"] .pd-content{padding:12px}.pd-frame[data-product-demo="inspector"] .pd-inspector{min-height:0}.pd-frame[data-product-demo="inspector"] .pd-editor{background:linear-gradient(135deg,#07101a,#050910)}
  @keyframes pdBlink{50%{opacity:0}}
  @media(max-width:720px){.pd-app{grid-template-columns:1fr;min-height:0}.pd-sidebar{display:none}.pd-window__title{max-width:160px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pd-toolbar{height:38px;padding:0 10px}.pd-chip:not(.pd-chip--safe){display:none}.pd-content{padding:9px}.pd-grid-2,.pd-review,.pd-sql-layout,.pd-frame--compact .pd-grid-2{grid-template-columns:1fr}.pd-stack{gap:8px}.pd-grid-2,.pd-review,.pd-sql-layout{gap:8px;margin-top:8px}.pd-review__row{grid-template-columns:64px 1fr}.pd-metric-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:5px}.pd-metric:last-child{grid-column:auto}.pd-metric{padding:8px}.pd-metric strong{font-size:13px}.pd-app .pd-table th,.pd-app .pd-table td{padding:6px;font-size:7px}.pd-inspector{grid-template-columns:1fr;min-height:0}.pd-inspector__files{display:none}.pd-frame--compact .pd-stack:last-child{display:grid}.pd-frame--evidence .pd-table th:nth-child(3),.pd-frame--evidence .pd-table td:nth-child(3){display:none}}
  @media(max-width:420px){.pd-frame{border-radius:18px}.pd-window{height:32px;padding-inline:10px}.pd-window__status{display:none}.pd-toolbar{height:36px}.pd-toolbar__title{font-size:10px}.pd-content,.pd-frame--compact .pd-content{padding:8px}.pd-query{padding:8px;font-size:9px}.pd-metric-grid{grid-template-columns:1fr 1fr}.pd-metric:last-child{grid-column:span 2}.pd-card__head{min-height:31px;padding-inline:8px}.pd-chart{height:92px;padding-top:14px}.pd-answer{padding:10px}.pd-source{margin-top:7px}.pd-frame--evidence .pd-toolbar{height:34px}.pd-frame--evidence .pd-content{padding:7px}.pd-editor__body{padding:8px 0}.pd-editor__foot{margin-bottom:8px}.pd-actions{margin-top:0}}
  @media(prefers-reduced-motion:reduce){.pd-query__cursor{animation:none}}
`;

function ProductWindowBar({ mode }: { mode: ProductDemoMode }) {
  return <div className="pd-window"><span className="pd-window__dot"/><span className="pd-window__dot"/><span className="pd-window__dot"/><span className="pd-window__title pd-mono">QueryMind · 기업 · ERP</span>{mode !== "evidence" && <span className="pd-window__status pd-mono"><i/>read-only</span>}</div>;
}

function ProductSidebar({ active }: { active: ProductDemoView }) {
  return <aside className="pd-sidebar" aria-label="제품 데모 메뉴"><div className="pd-brand"><span className="pd-brand__mark">Q</span>QueryMind</div><div className="pd-side-label pd-mono">WORKSPACE</div><nav className="pd-nav">{(Object.keys(VIEW_META) as ProductDemoView[]).map(key => { const item=VIEW_META[key]; const Icon=item.icon; return <span key={key} className={`pd-nav__item${active===key?" pd-nav__item--active":""}`}><Icon/>{item.label}</span>; })}</nav><div className="pd-sidebar__foot pd-mono">ERP-PROD-01<br/>policy sync · 2m ago</div></aside>;
}

function ProductWorkspace({ view, children }: { view: ProductDemoView; children: ReactNode }) {
  const meta=VIEW_META[view]; const Icon=meta.icon;
  return <section className="pd-workspace"><header className="pd-toolbar"><div className="pd-toolbar__title"><Icon/>{meta.label}</div><span className="pd-chip"><Database size={9}/>광주교대학사행정(합성)</span><span className="pd-chip pd-chip--safe"><i/>read-only</span><span className="pd-avatar">AN</span></header><div className="pd-content">{children}</div></section>;
}

function AskResultView() {
  const rows=[["종합","518명"],["학습보조강사","267명"],["수업","265명"],["참관","231명"]];
  return <><div className="pd-query"><Sparkles/>2026년 교육실습 구분별 배정 인원은?<span className="pd-query__cursor"/></div><div className="pd-grid-2"><div className="pd-stack"><div className="pd-card pd-answer"><div className="pd-answer__lead"><Sparkles/><span>배정 인원 1위는 <strong>종합(518명)</strong>입니다. 전체 합계는 <strong>1,281명</strong>입니다.</span></div><div className="pd-source"><span>enrollment</span><span>practice_assignment</span><span>2026학년도</span></div></div><div className="pd-card"><div className="pd-card__head"><Table2 size={11}/>결과 테이블<span>4 rows</span></div><table className="pd-table"><thead><tr><th>실습 구분</th><th>배정 인원</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td>{r[0]}</td><td className="pd-value">{r[1]}</td></tr>)}</tbody></table></div></div><div className="pd-stack"><div className="pd-card"><div className="pd-card__head"><BarChart3 size={11}/>배정 인원<span>명</span></div><div className="pd-chart"><div className="pd-bars">{[100,52,51,45].map((h,i)=><div key={i} className="pd-bar" style={{height:`${h}%`}}/>)}</div></div></div><div className="pd-card"><div className="pd-card__head"><FileCheck2 size={11}/>근거<span>검증됨</span></div><div className="pd-answer"><div className="pd-kicker"><ShieldCheck/>SQL · 출처 · 감사 로그 연결</div></div></div></div></div></>;
}

function HitlReviewView() {
  return <><div className="pd-query"><CircleAlert/>최근 3년 장학금 수혜 학생의 상세 명단을 보여줘</div><div className="pd-review"><div className="pd-card"><div className="pd-card__head"><Code2 size={11}/>실행 대기 SQL<span>Q-2026-0715-0842</span></div><div className="pd-code"><span className="kw">SELECT</span> student_id, department, scholarship_type{"\n"}<span className="kw">FROM</span> scholarship_recipient{"\n"}<span className="kw">WHERE</span> award_year &gt;= <span className="st">'2024'</span>;</div><div className="pd-gates"><span className="pd-gate"><Check/>읽기 전용</span><span className="pd-gate"><Check/>비용 게이트</span><span className="pd-gate" style={{color:"#fbbf24"}}><Clock3/>담당자 검토</span></div></div><aside className="pd-card pd-review__panel"><div className="pd-kicker"><UserCheck/>HITL REVIEW</div><div className="pd-review__row"><b>요청자</b><span>김분석 · 기획팀</span></div><div className="pd-review__row"><b>민감도</b><span>개인 식별 가능</span></div><div className="pd-review__row"><b>결과 범위</b><span>1,842 rows 예상</span></div><div className="pd-risk">개별 학생 식별자가 포함되어 실행 전 승인이 필요합니다.</div><div className="pd-actions"><button className="pd-action">반려</button><button className="pd-action pd-action--primary"><Check/>승인</button></div></aside></div></>;
}

function SqlResultView() {
  return <><div className="pd-query"><Code2/>이번 달 거래처별 수주 금액 알려줘</div><div className="pd-sql-layout"><div className="pd-card"><div className="pd-card__head"><Code2 size={11}/>생성 SQL<span>validated · 42ms</span></div><div className="pd-code"><span className="kw">SELECT</span> customer_name, <span className="kw">SUM</span>(order_amount) <span className="kw">AS</span> total{"\n"}<span className="kw">FROM</span> orders{"\n"}<span className="kw">WHERE</span> order_month = <span className="st">:month</span>{"\n"}<span className="kw">GROUP BY</span> customer_name{"\n"}<span className="kw">ORDER BY</span> total <span className="kw">DESC</span>;</div><div className="pd-gates"><span className="pd-gate"><Check/>SELECT only</span><span className="pd-gate"><Check/>RLS applied</span><span className="pd-gate"><Check/>cost 18</span></div></div><aside className="pd-card pd-lineage"><div className="pd-kicker"><Database/>SOURCE LINEAGE</div><div className="pd-lineage__node"><b>erp.orders</b><span>order_id · customer_id · amount</span></div><div className="pd-lineage__arrow">↓</div><div className="pd-lineage__node"><b>erp.customers</b><span>customer_id · customer_name</span></div><div className="pd-lineage__arrow">↓</div><div className="pd-lineage__node"><b>result.view_0842</b><span>5 aggregate rows</span></div></aside></div></>;
}

function DashboardView() {
  return <><div className="pd-metric-grid"><div className="pd-card pd-metric"><span>이번 달 수주</span><strong>₩8.42억</strong><em>↑ 12.4%</em></div><div className="pd-card pd-metric"><span>활성 거래처</span><strong>128</strong><em>↑ 6곳</em></div><div className="pd-card pd-metric"><span>평균 응답 시간</span><strong>1.8초</strong><em>↓ 0.3초</em></div></div><div className="pd-grid-2"><div className="pd-card"><div className="pd-card__head"><BarChart3 size={11}/>월별 수주 추이<span>최근 6개월</span></div><div className="pd-chart"><div className="pd-bars">{[48,62,57,76,69,92].map((h,i)=><div key={i} className="pd-bar" style={{height:`${h}%`}}/>)}</div></div></div><div className="pd-card"><div className="pd-card__head"><Database size={11}/>질문 유형<span>1,204건</span></div><div className="pd-donut"><svg viewBox="0 0 42 42" aria-label="질문 유형 도넛 차트"><circle cx="21" cy="21" r="15.9" fill="none" stroke="#182434" strokeWidth="5"/><circle cx="21" cy="21" r="15.9" fill="none" stroke="#38bdf8" strokeWidth="5" strokeDasharray="48 52" strokeDashoffset="25"/><circle cx="21" cy="21" r="15.9" fill="none" stroke="#2563eb" strokeWidth="5" strokeDasharray="31 69" strokeDashoffset="77"/><text x="21" y="23" textAnchor="middle">1.2K</text></svg></div><div className="pd-legend"><span><i style={{background:"#38bdf8"}}/>수주·매출 48%</span><span><i style={{background:"#2563eb"}}/>운영 현황 31%</span><span><i style={{background:"#334155"}}/>기타 21%</span></div></div></div></>;
}

function AuditLogView() {
  const rows=[["09:42:18","김분석","거래처별 수주 금액","완료"],["09:38:04","박기획","예산 집행률","완료"],["09:31:27","이운영","학생 상세 명단","검토"],["09:22:11","최관리","월별 등록 현황","완료"],["09:14:53","정감사","사용자 권한 변경","차단"]];
  return <><div className="pd-query"><Search/>질문, 사용자, Query ID 검색</div><div className="pd-card" style={{marginTop:10}}><div className="pd-card__head"><ListChecks size={11}/>감사 이벤트<span>오늘 · 1,284 events</span></div><table className="pd-table"><thead><tr><th>시간</th><th>사용자</th><th>요청</th><th>상태</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td className="pd-mono">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td><span className={`pd-status${r[3]==="검토"?" pd-status--wait":r[3]==="차단"?" pd-status--deny":""}`}><i/>{r[3]}</span></td></tr>)}</tbody></table></div><div className="pd-grid-2"><div className="pd-card pd-answer"><div className="pd-kicker"><ShieldCheck/>IMMUTABLE LOG</div><div className="pd-answer__lead" style={{marginTop:8}}><FileCheck2/><span>질문 원문, 생성 SQL, 정책 판정, 결과 행 수를 하나의 Query ID로 연결합니다.</span></div></div><div className="pd-card pd-answer"><div className="pd-kicker"><Clock3/>RETENTION</div><div className="pd-answer__lead" style={{marginTop:8}}><Database/><span><strong>365일</strong> 보관 · 내보내기 승인 필요</span></div></div></div></>;
}

function SqlInspectorView() {
  return <div className="pd-card pd-inspector"><aside className="pd-inspector__files"><div className="pd-kicker">SCHEMA</div><span>orders</span><span>customers</span><span>order_items</span><span>departments</span><span>users</span></aside><section className="pd-editor"><div className="pd-editor__tabs"><span>query_0842.sql</span><span>explain plan</span></div><div className="pd-editor__body"><div className="pd-lines pd-mono">1<br/>2<br/>3<br/>4<br/>5<br/>6<br/>7</div><pre className="pd-mono"><span className="kw">SELECT</span>{"\n  "}c.customer_name,{"\n  "}<span className="kw">SUM</span>(o.order_amount) <span className="kw">AS</span> total{"\n"}<span className="kw">FROM</span> orders o{"\n"}<span className="kw">JOIN</span> customers c <span className="kw">ON</span> c.id = o.customer_id{"\n"}<span className="kw">WHERE</span> o.order_month = <span className="st">:month</span>{"\n"}<span className="kw">GROUP BY</span> c.customer_name;</pre></div><div className="pd-editor__foot"><ShieldCheck size={10}/>SELECT only · RLS customer_scope applied · estimated 42ms</div><div className="pd-actions" style={{padding:"0 10px 10px",justifyContent:"flex-end"}}><button className="pd-action" style={{flex:"0 1 90px"}}>포맷</button><button className="pd-action pd-action--primary" style={{flex:"0 1 110px"}}><Play/>검증 실행</button></div></section></div>;
}

function ViewRenderer({ view }: { view: ProductDemoView }) {
  switch(view){case "ask":return <AskResultView/>;case "hitl":return <HitlReviewView/>;case "sql":return <SqlResultView/>;case "dashboard":return <DashboardView/>;case "audit":return <AuditLogView/>;case "inspector":return <SqlInspectorView/>;}
}

export function ProductAppShell({ view, mode="full" }: { view: ProductDemoView; mode?: ProductDemoMode }) {
  return <div className={`pd-frame pd-frame--${mode}`} data-product-demo={view} data-demo-mode={mode}><style>{PRODUCT_DEMO_STYLES}</style><ProductWindowBar mode={mode}/><div className="pd-app"><ProductSidebar active={view}/><ProductWorkspace view={view}><ViewRenderer view={view}/></ProductWorkspace></div></div>;
}

export function ProductDemoFrame({ view, mode="full", className="" }: { view: ProductDemoView; mode?: ProductDemoMode; className?: string }) {
  return <div className={className}><ProductAppShell view={view} mode={mode}/></div>;
}
